site_name: SDI Genomics Hubs
repo_name: wzheng0520/genomics_web
repo_url: https://wzheng0520.github.io/genomics_web/
site_url: https://sdi.genomics.hubs.altoslabs.com
nav:
    - Home: index.md
    - Genomics Document Page - Lab: document.md
    - On-site data processing: onsite.md
    - CRO data processing: cro.md
    - Data Browser: data.md
theme: readthedocs